# Generated by Django 3.1.3 on 2020-12-14 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login_in', models.DateTimeField(default=datetime.date(2020, 12, 14))),
                ('refresh_token', models.CharField(max_length=36)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'jwt_refresh_token',
                'managed': True,
            },
        ),
    ]
